spring :
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/TTT
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  redis:
    host: localhost
    port: 6380
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
logging:
  level:
    root: info




jwt:
  #  be11-2nd-4dollorExit-TikTakTalkbe11-2nd-4dollorExit-TikTakTalkbe11-2nd-4dollorExit-TikTakTalk
  secretKey: xxxxxxxxx
  expiration: 3000 #3000?
  #  tttisthecommunitysiteforstudentofhanhwatttisthecommunitysiteforstudentofhanhwatttisthecommunitysiteforstudentofhanhwa
  secretKeyRt: yyyyyyy
  #  200일
  expirationRt: 288000


cloud:
  aws:
    credentials:
      access-key: xxxxx
      secret-key: yyyyyyyy
    region:
      static: ap-northeast-2
    s3:
      bucket: tiktaktok-images

# 휴대폰 API 관련설정
coolsms:
  apiKey: xxxxx
  apiSecret: yyyyyy
  fromNumber: zzzzzzz # 발신번호

# oauth 로그인 설정
oauth:
  google:
    client-id: xxxxxxx
    client-secret : zzzzzz
    redirect-url: http://localhost:3000/oauth/google/redirect
  kakao:
    client-id: xxxxxxx
    redirect-url: http://localhost:3000/oauth/kakao/redirect
