spring :
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/TTT
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  redis:
    host: localhost
    port: 6380
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
logging:
  level:
    root: info




jwt:
  #  be11-2nd-4dollorExit-TikTakTalkbe11-2nd-4dollorExit-TikTakTalkbe11-2nd-4dollorExit-TikTakTalk
  secretKey: YmUxMS0ybmQtNGRvbGxvckV4aXQtVGlrVGFrVGFsa2JlMTEtMm5kLTRkb2xsb3JFeGl0LVRpa1Rha1RhbGtiZTExLTJuZC00ZG9sbG9yRXhpdC1UaWtUYWtUYWxr
  expiration: 3000 #3000?
  #  tttisthecommunitysiteforstudentofhanhwatttisthecommunitysiteforstudentofhanhwatttisthecommunitysiteforstudentofhanhwa
  secretKeyRt: dHR0aXN0aGVjb21tdW5pdHlzaXRlZm9yc3R1ZGVudG9maGFuaHdhdHR0aXN0aGVjb21tdW5pdHlzaXRlZm9yc3R1ZGVudG9maGFuaHdhdHR0aXN0aGVjb21tdW5pdHlzaXRlZm9yc3R1ZGVudG9maGFuaHdh
  #  200일
  expirationRt: 288000


cloud:
  aws:
    credentials:
      access-key: AKIAWOOXTW7IOZGTJCMC
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: tiktaktok-images

# 휴대폰 API 관련설정
coolsms:
  apiKey: "NCSFBPNCDNGAMQAW"
  apiSecret: "UHFIXQ58FGPRNBAAMCDFB0JSVEQTXOSA"
  fromNumber: "01057105689" # 발신번호

# oauth 로그인 설정
oauth:
  google:
    client-id: 906300369324-bj1gkpi8ltlkr4jjq40pq8orl90ulvbg.apps.googleusercontent.com
    client-secret : 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
    redirect-url: http://localhost:3000/oauth/google/redirect
  kakao:
    client-id: d4582d3d057eb4fcd270886537698cd9
    redirect-url: http://localhost:3000/oauth/kakao/redirect
