apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttt-backend
spec:
  selector:
    matchLabels:
      app: ttt-backend
  template:
    metadata:
      labels:
        app: ttt-backend
    spec:
      containers:
      - name: ttt-backend
        image: 443370682320.dkr.ecr.ap-northeast-2.amazonaws.com/ttt:latest
        ports:
        - containerPort: 8080
        resources:
        # 컨테이너가 사용할수 있는 리소스의 최대치
          limits:
            cpu: "1"
            memory: "500Mi"
        # 컨테이너가 시작될떄 보장받아야 하는 최소 자원
          requests:
            cpu: "0.5"
            memory: "250Mi"
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: DB_HOST
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: DB_PW
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: AWS_SECRET
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: JWT_KEY              
        - name: JWT_KEYRT
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: JWT_KEYRT
        - name: COOL_API
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: COOL_API
        - name: COOL_SECRET
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: COOL_SECRET
        - name: COOL_NUMBER
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: COOL_NUMBER  
        - name: GOOGLE_ID
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: GOOGLE_ID
        - name: GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: GOOGLE_SECRET
        - name: KAKAO_ID
          valueFrom:
            secretKeyRef:
              name: ttt-secrets
              key: KAKAO_ID

        # 컨테이너 상태 확인 
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /ttt/user/check
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ttt-backend-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ttt-backend