apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ttt-server-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1 
    cert-manager.io/cluster-issuer: my-issuer
spec:
  tls:
  - hosts:
    - "server.tiktaktok.site"
    secretName: server-tiktaktok-com-tls
  rules:
  - host: server.tiktaktok.site
    http:
      paths:
      - path: /(.*) 
        pathType: Prefix
        backend:
          service:
            name: ttt-backend-service
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: my-issuer
spec:
  acme:
  # 인증서 서버 주소. 해당 서버의 리소스를 통해 인증서 발행
    server: https://acme-v02.api.letsencrypt.org/directory
  # 인증서 만료 또는 갱신 필요시 알람 email
    email: kynia0506@naver.com
    privateKeySecretRef:
      name: my-issuer
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-tiktaktok-com-tls
spec:
  secretName: server-tiktaktok-com-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: server.tiktaktok.site
  dnsNames:
  - server.tiktaktok.site